---
- hosts: my_servers
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - /var/lib/jenkins/workspace/test/ansible/environments/{{env}}/group_vars/main.yml
  roles:
    - tomcat_install
    - war_deploy