---
- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/local/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=https://downloads.apache.org/tomcat/tomcat-7/v7.0.104/bin/apache-tomcat-7.0.104.tar.gz dest=/tmp

- name: create directory for tomcat
  file: path=/usr/local/tomcat state=directory

- name: Extract archive
  unarchive: src=/tmp/apache-tomcat-7.0.104.tar.gz dest=/usr/local/tomcat copy=no

- name: Change ownership of Tomcat installation
  file: path=/usr/local/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/local/tomcat/apache-tomcat-7.0.104/conf/

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/local/tomcat/apache-tomcat-7.0.104/conf/

- name: push the service file to systemd path
  copy: src=tomcat.service dest=/etc/systemd/system/

- name: start the tomcat
  service: name=tomcat state=restarted enabled=yes
